### ISSUE TITLE
vc++ 16.8.0. Preview 4.0 does not require /await

### ISSUE THREAD

**Issue by mediabuff** [andreasbuhr/cppcoro#11]
line 13 in Ccppcoro\cmake\FindCppcoroCoroutines.cmake

set(Coroutines_EXTRA_FLAGS "/await")

**Comment by andreasbuhr** [comment]
While MSVC 16.8.0 does not require /await, it supports it. We do not know whether the user wants C++20-coroutines or coroutines-ts (using /await). We thus have to rely on the user to specify on the command line what she wants.
