### ISSUE TITLE
vc++ cmake - cannot find tests-main.lib

### ISSUE THREAD

**Issue by mediabuff** [andreasbuhr/cppcoro#12]

**Comment by andreasbuhr** [comment]
Hello, thanks a lot for your issue report. Could you please describe what you did to hit this problem?

**Comment by mediabuff** [comment]
Just compile under cmake - VC++

**Comment by andreasbuhr** [comment]
Can you provide a set of commands you executed? Which branch are you working on?

**Comment by Garcia6l20** [comment]
This can be resolved by setting tests-lib to be STATIC instead of SHARED.
Fix coming soon.

**Comment by andreasbuhr** [comment]
I think this is fixed now?

**Comment by Garcia6l20** [comment]
Yes fixed in https://github.com/andreasbuhr/cppcoro/pull/15

**Comment by andreasbuhr** [comment]
Great.
