### ISSUE TITLE
vc++ 16.8.0 Preview 4 - support for c++ 20

### ISSUE THREAD

**Issue by mediabuff** [andreasbuhr/cppcoro#13]
add set(CMAKE_CXX_STANDARD 20) in CmakeLIsts.ext

**Comment by andreasbuhr** [comment]
Hi, thanks a lot for your issue report. Tobias is currently working on this problem in https://github.com/andreasbuhr/cppcoro/pull/10. Could you please have a look and see whether this solves your problem?

**Comment by andreasbuhr** [comment]
Hi @mediabuff , we now decided to leave the selection of C++ version to the user, i.e. when running cmake, the user should specify on the command line which C++ version she wants. This is required as we do not know what the user wants.
