### ISSUE TITLE
MSVC compile error

### ISSUE THREAD

**Issue by Micha-2021** [andreasbuhr/cppcoro#38]
Compiling:
async_auto_reset_event_tests.cpp
async_generator_tests.cpp
async_latch_tests.cpp
async_manual_reset_event_tests.cpp
sequence_barrier_tests.cpp
multi_producer_sequencer_tests.cpp
scheduling_operator_tests.cpp

produce the error: the expression "co_await promise.final_suspend()" may not throw an exception
in task.hpp

MSVC 19.28.29913 for x64

**Comment by Philpax** [comment]
I've put up a prospective fix at #39, fyi

**Comment by andreasbuhr** [comment]
thx again, fixed
