### ISSUE TITLE
Windows/MinGW:  implicit instantiation of undefined template on socket_helpers

### ISSUE THREAD

**Issue by kassane** [andreasbuhr/cppcoro#72]
My fork
build log: https://github.com/kassane/cppcoro/actions/runs/5326844101

```bash
 clang failed with stderr: D:\a\cppcoro\cppcoro\lib\socket_helpers.cpp:52:43: error: implicit instantiation of undefined template 'std::reference_wrapper<sockaddr_storage>'
C:\hostedtoolcache\windows\zig\master\x64\lib\libcxx\include/__functional/unwrap_ref.h:25:7: note: template is declared here
D:\a\cppcoro\cppcoro\lib\socket_helpers.cpp:77:33: error: no viable overloaded '='
C:\hostedtoolcache\windows\zig\master\x64\lib\libc\include\any-windows-any/ws2def.h:28:16: note: candidate function (the implicit copy assignment operator) not viable: no known conversion from 'int' to 'const _SCOPE_ID' for 1st argument
C:\hostedtoolcache\windows\zig\master\x64\lib\libc\include\any-windows-any/ws2def.h:28:16: note: candidate function (the implicit move assignment operator) not viable: no known conversion from 'int' to '_SCOPE_ID' for 1st argument
D:\a\cppcoro\cppcoro\lib\socket_helpers.cpp:52:43: warning: unused parameter 'address' [-Wunused-parameter]
```

**Comment by andreasbuhr** [comment]
Your title talks about MinGW, but the error message states you are compiling with Clang. Can you clarify please?
What standard library do you use? The error message states that "C:\hostedtoolcache\windows\zig\master\x64\lib\libcxx" is used. What kind of library is that?

**Comment by kassane** [comment]
The title is not wrong! Target is **mingw** equivalent to **llvm-mingw** or **msys2/clang64** both use `libc++` instead of `libstdc++`.

zig toolchain is **pure-llvm** (builtin-tools: clang/++ + libcxx + libunwind + (custom)-libcompiler-rt + lld or [zld(macOS only)](https://github.com/kubkon/zld)])) based and currently for windows the default target is mingw (x86,amd64,arm64). However LLVM doesn't provide a full mingw support, with no add-on libraries like posix support.

Error happens with this function.
https://github.com/andreasbuhr/cppcoro/blob/6863ac6f2e2e421c289460fc7cc88f3dda2d5fc8/lib/socket_helpers.cpp#L50-L83

### References:

- [Bootstrapping Uber’s Infrastructure on arm64 with Zig](https://www.uber.com/en-BR/blog/bootstrapping-ubers-infrastructure-on-arm64-with-zig/)
- [`zig cc`: a Powerful Drop-In Replacement for GCC/Clang](https://andrewkelley.me/post/zig-cc-powerful-drop-in-replacement-gcc-clang.html)
- [zig cc compatibility with clang](https://github.com/ziglang/zig/wiki/zig-cc-compatibility-with-clang)
- [awesome zig - C++ zig-package libraries](https://github.com/catdevnull/awesome-zig#cc-libraries-packaged-for-zig)

**Comment by andreasbuhr** [comment]
Thanks for clarifying.

The first error says that std::reference_wrapper is undefined. Does it help to #include <functional> in cppcoro/lib/socket_helpers.cpp?

**Comment by kassane** [comment]
> Thanks for clarifying.
> 
> The first error says that std::reference_wrapper is undefined. Does it help to `#include <functional>` in cppcoro/lib/socket_helpers.cpp?

keep:

```bash
clang failed with stderr: /home/kassane/Documentos/cppcoro/lib/socket_helpers.cpp:78:33: error: no viable overloaded '='
/home/kassane/zig/0.11.0-dev.3773+438d68091/files/lib/libc/include/any-windows-any/ws2def.h:28:16: note: candidate function (the implicit copy assignment operator) not viable: no known conversion from 'int' to 'const _SCOPE_ID' for 1st argument
/home/kassane/zig/0.11.0-dev.3773+438d68091/files/lib/libc/include/any-windows-any/ws2def.h:28:16: note: candidate function (the implicit move assignment operator) not viable: no known conversion from 'int' to '_SCOPE_ID' for 1st argument
```

**Comment by andreasbuhr** [comment]
I did not try mingw.

in https://github.com/tpn/winsdk-10/blob/9b69fd26ac0c7d0b83d378dba01080e93349c2ed/Include/10.0.10240.0/shared/ws2def.h#L625C1-L625C42 you can see that SCOPEID_UNSPECIFIED_INIT is defined to be "{ 0 }". Could you try that? 

I don't know the right escaping, but something like 
-DSCOPEID_UNSPECIFIED_INIT={0}
or
-DSCOPEID_UNSPECIFIED_INIT=\{0\}
or so

**Comment by kassane** [comment]
Fine!!

Now...

```bash
error: lld-link: undefined symbol: WaitOnAddress
    note: referenced by /home/kassane/Documentos/cppcoro/lib/lightweight_manual_reset_event.cpp:52
    note:               cppcoro.lib(lightweight_manual_reset_event.obj):(cppcoro::detail::lightweight_manual_reset_event::wait())
error: lld-link: undefined symbol: WakeByAddressAll
    note: referenced by /home/kassane/Documentos/cppcoro/lib/lightweight_manual_reset_event.cpp:30
    note:               cppcoro.lib(lightweight_manual_reset_event.obj):(cppcoro::detail::lightweight_manual_reset_event::set())
```
`synchapi.h` feature...

**Comment by andreasbuhr** [comment]
Could you double-check that you link to synchronization.lib ?

**Comment by kassane** [comment]
> Could you double-check that you link to synchronization.lib ?

No have `synchonization.lib` on mingw.

Fixed - add in `config.hpp`:
```c
#ifdef __MINGW32__
#define _WIN32_WINNT 0x0601
#endif
```
