### ISSUE TITLE
Can not run non-experimental <coroutine>

### ISSUE THREAD

**Issue by Brendan-Jacobson1** [andreasbuhr/cppcoro#85]
If I try to compile my code with cppcoro I get 

C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\experimental/coroutine(37,1): fatal error C1189: #error:  The <experimental/coroutine> and <experimental/resumable> headers are only supported with /await and implement pre-C++20 coroutine support. Use <coroutine> for standard C++20 coroutines. 

I can't use /await since I want to use cppcoro with the latest boost asio. My code doesn't have <experimental/coroutine> it has #include <coroutine>. It looks like this branch chooses #include <experimental/coroutine> or  #include <coroutine> based on something. The readme says "Automatically including 'coroutine' or 'experimental/coroutine', depending on compiler." Has anybody gotten this to work with their compiler? Is there a list of compilers that use non-experimental 'coroutine'?

Im not sure if this is what https://github.com/andreasbuhr/cppcoro/tree/unify_experimental_includes is for. I did try to build it but when I followed the instructions cake.bat, I don't think cake.bat did anything

"""
\cppcoro>cake.bat

Build succeeded.
Build took 0:00:00.172.
"""

no dll was created

Has anybody gotten cppcoro to run with <coroutines>?
I'm using MSVC but if I need to change the compiler I can (preferably one that works on windows and maybe linux).

**Comment by andreasbuhr** [comment]
Please check which branch you are using. This repository does not contain a file named "cake.bat". It got deleted years ago.

**Comment by Brendan-Jacobson1** [comment]
Most of my time trying to get it to work has been on the main branch that uses cmake to build. The unify_experimental_includes was just the last thing I tried.

**Comment by andreasbuhr** [comment]
Could you please provide the CMake output when running CMake for the first time in a freshly created build folder? In the main branch?

**Comment by Brendan-Jacobson1** [comment]
The issue was not caused by the repo and has been resolved.
